// Auto-generated by tools/build_aux_pool.py - do not edit by hand.
#pragma once

#include <stdint.h>

static const uint8_t AUX_N_POOL_JUSTIFY_VT3_DEFAULT = 0x01;
static const uint8_t AUX_N_POOL_JUSTIFY_VT4_ENHANCED = 0x05;
static const uint32_t AUX_N_POOL_JUSTIFY_OFFSET_COUNT = 20;
static const uint32_t AUX_N_POOL_JUSTIFY_OFFSETS[AUX_N_POOL_JUSTIFY_OFFSET_COUNT] = {80, 111, 142, 173, 204, 235, 267, 299, 330, 361, 392, 423, 454, 486, 518, 549, 580, 611, 642, 674};
